In [1]:
import geopandas as gpd
from sqlalchemy import create_engine

In [3]:
district_path = "../data/raw/meghalaya/boundaries/district/district.shp"  # change name if needed

gdf = gpd.read_file(district_path)
gdf.head()

,id,name,geometry
0,17273285,East Garo Hills,"POLYGON ((90.69791 25.8207, 90.6979 25.82065, ..."
1,17274293,East Khasi Hills,"POLYGON ((92.14364 25.6702, 92.14379 25.6702, ..."
2,17275295,West Jaintia Hills,"POLYGON ((92.38356 25.74871, 92.38296 25.74801..."
3,17276294,Ri Bhoi,"POLYGON ((91.83382 26.11576, 91.83394 26.11573..."
4,17277291,South Garo Hills,"POLYGON ((90.79079 25.49386, 90.79255 25.49069..."

In [4]:
print(gdf.crs)

EPSG:4326

In [5]:
gdf = gdf.to_crs(epsg=4326)
print(gdf.crs)

EPSG:4326

In [6]:
gdf.columns

Index(['id', 'name', 'geometry'], dtype='object')

In [7]:
gdf["district_name"] = gdf["name"].astype(str).str.strip().str.title()
gdf[["id", "name", "district_name"]].head()

         id                name       district_name
0  17273285     East Garo Hills     East Garo Hills
1  17274293    East Khasi Hills    East Khasi Hills
2  17275295  West Jaintia Hills  West Jaintia Hills
3  17276294             Ri Bhoi             Ri Bhoi
4  17277291    South Garo Hills    South Garo Hills

In [9]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:7654@localhost:5433/meghalaya_geo_llm")

engine

Engine(postgresql://postgres:***@localhost:5433/meghalaya_geo_llm)

In [10]:
gdf.to_postgis(
    name="meghalaya_districts",
    con=engine,
    if_exists="replace",
    index=False
)